apiVersion: v1
kind: Service
metadata:
  labels:
    app: web2
  name: web2
  namespace: hosting
spec:
  ports:
  - nodePort: 32459
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web2
  sessionAffinity: None
  type: NodePort
