apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: web2
  name: web2
  namespace: hosting
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: web2
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 30
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
