apiVersion: v1
kind: Service
metadata:
  labels:
    app: sitelb
  name: sitelb
  namespace: temp
spec:
  ports:
  - name: "80"
    nodePort: 30193
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sitelb
  sessionAffinity: None
  type: NodePort
